import { createApp } from 'vue'
import App from '/@/App.vue'
import router from './router'
import store from './store'
import VueViewer from 'v-viewer'
import 'virtual:windi.css'
import '/@/styles/index.css'
import 'gitart-vue-dialog/dist/style.css'
import 'viewerjs/dist/viewer.css'
createApp(App).use(router).use(store).use(VueViewer).mount('#app')
